name: Lint Code

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Sprawdza repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Ustawienie wersji Pythona (dostosuj wersję do swojego projektu)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Instalacja zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Uruchomienie Black w trybie sprawdzania (bez automatycznej modyfikacji plików)
      - name: Run Black
        run:  black --check . --diff --color
